### ISSUE TITLE
Overly-dark status line for inactive split

### ISSUE THREAD

**Issue by reedes** [reedes/vim-colors-pencil#12]
Should be only subtly darker.

![screen shot 2014-09-06 at 6 31 41 am](https://cloud.githubusercontent.com/assets/6090039/4175153/dddabbae-35c1-11e4-80ab-24593a582ed5.png)

**Comment by daliusd** [comment]
I'm not sure how to reproduce this one and I see it is quite old one - so I think it can be closed. Here how it looks with airline:

![image](https://user-images.githubusercontent.com/1944737/98526540-8bb63880-2282-11eb-817b-10ac5df38546.png)

I have tried to reproduce with airline disabled but it is different in that case.
