### ISSUE TITLE
When installing with Vundle, doesn't copy the autoload folder

### ISSUE THREAD

**Issue by omrihar** [reedes/vim-colors-pencil#16]
When I install `vim-colors-pencil` with Vundle, the autoload and screenshots folders don't get cloned. This leads to problems with `vim-airline` since it can't find the pencil theme. 

I've seen some discussion on Vundle about doing a shallow clone of repositories to increase performance, etc.. so perhaps it's related to that.

**Comment by reedes** [comment]
Hmm. Is this recent Vundle behavior, because I'd used it for more than a year without any problems?

I'll see if I can reproduce this problem this weekend.

**Comment by omrihar** [comment]
I'm not sure this really is a Vundle problem - I saw some discussions about it in one of the issues on github (https://github.com/gmarik/Vundle.vim/issues/28) but I don't know if it was implemented. I only know that since I installed vim-colors-pencil (only recently) I got errors with airline because of the theme and when I dug in I discovered that the theme was not downloaded by Vundle. When I manually clone the repository and symlink to .bundle it works fine.

**Comment by omrihar** [comment]
I figured it out - it was my bad. Instead of putting `Bundle 'reedes/vim-colors-pencil'` in my `.vimrc` I put `Bundle 'vim-colors-pencil'` which meant it was cloning from vim-scripts instead of github. 
I guess it might be good to synchronize the two but this is the origin of my problem. I now changed my `.vimrc` file and everything works perfectly.

Thanks for the cool theme by the way!

**Comment by reedes** [comment]
Aha! A good point that I should refresh the vim-scripts version, which lags way behind the github version.
