### ISSUE TITLE
[Request][Airline Theme] Visual change when window has unsaved changes

### ISSUE THREAD

**Issue by kaldrenon** [reedes/vim-colors-pencil#18]
I'm really digging Pencil Dark, and overall I'm quite happy with it.

However, my previous CS used a very dramatically different set of colors for a changed buffer, and I really value that.

Pencil's Ailrline theme doesn't seem to support that:

No Edits
![No Edits](https://www.dropbox.com/s/pyy3d7d55bvvh8j/Screenshot%202015-04-17%2009.25.51.png?dl=1)

With Edits
![With Edits](https://www.dropbox.com/s/nugcgnv4elm6yx9/Screenshot%202015-04-17%2009.26.16.png?dl=1)

**Comment by daliusd** [comment]
I would close this one as screenshots do not show anymore and it is not clear where problem is.

Otherwise Pull Requests are welcome. Lastly it is possible to write your own Airline theme.
