### ISSUE TITLE
Alternative color scheme in screenshots?

### ISSUE THREAD

**Issue by PixelPirate** [reedes/vim-colors-pencil#21]
In the `screenshots` folder is a image showing a slightly different color scheme 
![Different colors](https://raw.githubusercontent.com/reedes/vim-colors-pencil/25536953c45b9de0fe99c64860874b36d8f60932/screenshots/vimscript-example.png)

This is definitely not pencil on light background, as that looks like this
<img width="846" alt="bildschirmfoto 2015-12-10 um 11 42 30" src="https://cloud.githubusercontent.com/assets/776450/11713341/221884f0-9f33-11e5-8ae8-b067ad394c74.png">

It does look really nice though, as I like the brighter comment color better. Is there any documentation on how to enable this alternative color scheme?

**Comment by reedes** [comment]
That screenshot looks to be from my early prototype based on the colors in the then-new 'pro' version of iAWriter.

This `pencil.vim` looks to be the most recent version of that prototype prior to the extensive rework: https://github.com/reedes/vim-colors-pencil/blob/2a5ceb36820164fa2ea653c01720f01124da7da9/colors/pencil.vim

You can copy and paste that into your own colors file.

Alternatively, you can fork and rework the current version to your liking. @mattly's layout should be fairly straightforward.

**Comment by PixelPirate** [comment]
Thank you so much, I will look into that!

**Comment by alerque** [comment]
Closing issue as there doesn't seem to be anything actionable left here, the question was answered.
