### ISSUE TITLE
problems installing

### ISSUE THREAD

**Issue by arnauldb** [reedes/vim-colors-pencil#23]
Hello,

could you explain to me how to install via Vundle and how to activate this theme ?

Thank you,

**Comment by OVlasiuk** [comment]
Put this in your .vimrc:

> Plugin 'reedes/vim-colors-pencil'

then, while in the same buffer with vimrc, run

> :source %
> :PluginInstall

For Vundle version < 0.10.2, replace "Plugin" with "Bundle". In order to activate, run

> :colorscheme pencil

in Vim; to make permanent, add this line to .vimrc.

**Comment by arnauldb** [comment]
thanks OVlasiuk.

That's what I did. I don't get the background as seen below however : 

![687474703a2f2f692e696d6775722e636f6d2f42594c4d6478352e6a7067](https://cloud.githubusercontent.com/assets/13196747/22402345/4c3693a4-e5f4-11e6-8ec4-f577d3ff6c34.jpeg)


Am I missing something ?

**Comment by OVlasiuk** [comment]
Do you have something like

> set background=light

in the .vimrc? Which of the two backgrounds doesn't work?

**Comment by arnauldb** [comment]
ok, thanks OVlasiuk, it is working now, I added 

> set background=light

to my .vimrc

**Comment by daliusd** [comment]
This one can be closed as well as question was answered.
