### ISSUE TITLE
distribute with Vim?

### ISSUE THREAD

**Issue by chrisbra** [reedes/vim-colors-pencil#25]
there is an [issue](https://github.com/vim/vim/issues/1665) open in the vim repository, to distribute more colorschemes with Vim. Would you kindly give your permission to distribute this colorscheme with Vim?

**Comment by reedes** [comment]
Yes, I grant permission. Happy to do so.

Pencil has an MIT-style license. Please let me know if I need to extend the license for distribution.

**Comment by chrisbra** [comment]
Thanks. Well, I can collect your file and send it to Bram, or you can do it. I would prefer if you can do it, since you know obviously best, when it is kind of stable enough and of course you will know when to send updated themes to Bram for inclusion. If you want to do it, mention the issue 1665 when sending it to Bram. Last Bram said, he would collect them and decide later what to bundle with Vim, so I cannot guarantee that it will be bundled later on.

**Comment by alerque** [comment]
Feel free. Reed is less active (not inactive) lately, and I have collaborator access here but no plans to do this myself. I think this will be up to somebody actually doing. Permission is already granted, so I don't think there is any point in tracking it in an issue here. If it happens it will happen in relation to a VIM issue. Closing this as it is not actionable here, but anybody wanting to tackle it on the VIM side is welcome to do so.
