### ISSUE TITLE
Portuguese accentuated characters are not rendered on Tmux

### ISSUE THREAD

**Issue by mrbig033** [reedes/vim-colors-pencil#26]
### My environment:
- [init.vim](https://hastebin.com/umagagecav.bash)
- [.tmux.conf](https://hastebin.com/qolufumaho.bash)
- terminator 1.90
- xfce4-terminal 0.8.3 (Xfce 4.12)
- NVIM v0.3.0-1029-g48967695c, Build type: RelWithDebInfo
- MX-Linux 17

### When it happens:

When I open a file both with Terminator and Xfce4-terminal, using Tmux in
combination with Neovim and only when I use either Stylus or Pencil colorschemes,
with or without options.

### What happens:

accentuated characters are not rendered unless I redraw the screen. The problem does 
not occur with other colorschemes in the same conditions. It occurs in different filetypes and
syntaxes. 

Example 1 (look at line 97):
![example1](https://user-images.githubusercontent.com/36245777/38888756-fbfb3522-4252-11e8-8de5-6850dc68fa54.png)

Example 2 (after I redraw the screen, the characters "ã" and "é" are now visible)
![example2](https://user-images.githubusercontent.com/36245777/38888757-fc20bdf6-4252-11e8-8335-46803e672567.png)

**Comment by alerque** [comment]
I'm pretty sure this bug is going to be upstream of the color scheme. Also I can't replicate it (tested in NeoVIM/Tmux in Alacritty/Termite). Are you still able to replicate this? Anybody?

**Comment by daliusd** [comment]
I can't reproduce it either:
![image](https://user-images.githubusercontent.com/1944737/98527416-ab019580-2283-11eb-9b32-745c78a27855.png)
