### ISSUE TITLE
Undercurl not working in terminal

### ISSUE THREAD

**Issue by BlueDrink9** [reedes/vim-colors-pencil#29]
I'm using kitty, and other themes have spelling undercurl but in markdown I just see misspelled words highlighted.
In MacVim it works fine.

**Comment by daliusd** [comment]
It looks like `else` part here need "gui" defined as well. This issue gave a hint: https://github.com/vim/vim/issues/6174

```
if has("gui_running")
  call s:h("SpellBad",    {"gui": s:sp_un, "sp": s:red})
  call s:h("SpellCap",    {"gui": s:sp_un, "sp": s:light_green})
  call s:h("SpellRare",   {"gui": s:sp_un, "sp": s:pink})
  call s:h("SpellLocal",  {"gui": s:sp_un, "sp": s:dark_green})
else
  call s:h("SpellBad",    {"gui": s:sp_un, "cterm": s:sp_un, "fg": s:red})
  call s:h("SpellCap",    {"gui": s:sp_un, "cterm": s:sp_un, "fg": s:light_green})
  call s:h("SpellRare",   {"gui": s:sp_un, "cterm": s:sp_un, "fg": s:pink})
  call s:h("SpellLocal",  {"gui": s:sp_un, "cterm": s:sp_un, "fg": s:dark_green})
endif
```

**Comment by alerque** [comment]
Yes, I think something like that needs to be added. Would either of you be interested in contributing a PR?

**Comment by alerque** [comment]
By the way I don't thing you even nede the if block, you should just be able to set all the possible values correctly for `gui`, `term`, and `cterm` and whatever environment is active will pick up the most relevant values.

**Comment by daliusd** [comment]
Is this project actually live? I could contribute PR but I would love to see more changes. E.g. diffs look bad in terminal with this theme but overall this is very nice theme.

**Comment by alerque** [comment]
Yes it's alive. Or at least it can be. I don't use this color scheme myself so I'm unlikely to put much dev time into it, but reedes gave me collaborator access to most of his plugins a while back (I use Pencil and others all day every day) and I'm happy to do PR review and merges. If you are an active user and want to fix/improve things I'll help get the contributions upstreamed.
