### ISSUE TITLE
Some way to make non-printing characters/tags darker?

### ISSUE THREAD

**Issue by subnut** [reedes/vim-colors-pencil#30]
tags like `<br>` `<sub> </sub>` 
non-printing characters like `&nbsp;`

Example from [ghostwriter](https://github.com/wereturtle/ghostwriter)

![image](https://user-images.githubusercontent.com/56714626/93092224-cc4b6880-f6bc-11ea-98f6-cd98a3f372a4.png)

notice how only `Cl`, `2`, etc printing characters are in the foreground color? The rest are in some kind of a faded color?
I guess that the faded  color can be obtained easily (ref. #7)
But I don't know anything about detecting the words/characters

Is it feasible?

**Comment by daliusd** [comment]
&nbsp; is highlighted already (at least for filetype=html)

![image](https://user-images.githubusercontent.com/1944737/98528633-3fb8c300-2285-11eb-9ee3-bba7156d0c64.png)

It is not clear what filetype are you dealing with in the first place. Here you can look how html syntax file looks like:
https://github.com/neovim/neovim/blob/master/runtime/syntax/html.vim

You can search through it and `<br>`, '<sub>` tags are not in it. So overall it seems you want to have custom syntax file in the first place. So it is not necessary colorscheme specific problem.

Here is example of simple syntax TODO file that might give idea how to write one:
https://github.com/daliusd/cfg/blob/master/.vim/syntax/todo.vim

Here is how result of syntax file looks like:
![image](https://user-images.githubusercontent.com/1944737/98530749-03d32d00-2288-11eb-8c6e-443c4fca7c58.png)

**Comment by daliusd** [comment]
My proposal is to close this issue as of now as I believe I have answered the question.

**Comment by alerque** [comment]
Just to expand on this a little: The issue with GhostWriter is most likely that the file type is not set to match the contents. No this color scheme (nor any color scheme) will not highlight things that are not defined in the file types' syntax. The scheme only adds colors to the syntax rules, it doesn't *define* the syntax rules.
