### ISSUE TITLE
Git Gutter background color different than normal background

### ISSUE THREAD

**Issue by mcookly** [reedes/vim-colors-pencil#36]
Is there any reason the gutter background color is a different shade than the normal background? For example:

<img src="https://user-images.githubusercontent.com/20271792/218262872-3baba24e-81dd-4c94-9386-6e9bf2c62d47.gif" width="300px">
<img src="https://user-images.githubusercontent.com/20271792/218262873-5fa714cd-e7a3-4105-8790-4fbbcbd2445e.gif" width="300px">

I know this is a pretty easy fix without modifying the source code. I'm just questioning the design decision and whether it should be adjusted to match the normal background.

**Comment by reedes** [comment]
I don't recall the specific motivation, but likely it was to contrast the border of the code area.
